<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Moneta' => array($vendorDir . '/moneta/webservice/src', $vendorDir . '/integrationmonitoring/moneta-php-sdk/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
);
